- name: remove old versions
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Update repository cache and ensure that APT works with HTTPS method
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install ca certificates if not already installed
  apt:
    name: ca-certificates
    state: present

- name: Add apt key for newest docker release
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: false
  when: add_repository_key is failed

- name: Add docker repository server to apt sources list
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update repository cache and install docker
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: configure logging
  copy:
    src: "daemon.json"
    dest: "/etc/docker"


- name: Make sure that docker starts on boot
  service:
    name: docker
    enabled: yes
    state: "started"

- name: install pip
  apt:
    name: python-pip
    state: latest

- name: install docker-py
  pip:
    name: docker-py
